source 'https://rubygems.org'
ruby '2.0.0'

gem 'rails', '4.1.1'
gem 'bootstrap-sass'
gem 'bcrypt-ruby'
gem 'will_paginate'
gem 'bootstrap-will_paginate'
gem 'font-awesome-rails'

gem 'protected_attributes' 

group :development, :test do
  gem 'sqlite3'
  gem 'rspec-rails'
end

gem 'turbolinks'
gem 'sass-rails'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder'

#for widnows machines 
platforms :mswin do
	gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw]
end

group :doc do
  gem 'sdoc', require: false
end

group :production do
  gem 'rails_12factor'
end